name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login on Docker
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/store-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/store-backend:latest
            docker rm -f store-backend
            docker run -d -p 8080:8080 -e DB_URL='${{ secrets.DB_URL }}' DB_USERNAME='${{ secrets.DB_USERNAME }}' DB_PASSWORD='${{ secrets.DB_PASSWORD }}' ALLOWED_ORIGINS='${{ secrets.ALLOWED_ORIGINS }}' OKTA_CLIENT_ID='${{ secrets.OKTA_CLIENT_ID }}' OKTA_ISSUER='${{ secrets.OKTA_ISSUER }}' STRIPE_SECRET='${{ secrets.STRIPE_SECRET }}' --name store-backend ${{ secrets.DOCKER_USERNAME }}/store-backend:latest